name: "OpenAI GPT"
inputs:
  input-artifact: 
    description: "Prompt para generar imagen"
    required: true
    type: string
  prompt-file: 
    description: "archivo de prompt"
    required: true
    type: string
  ouput-artifact:
    required: true
    type: string
  image-name:
    required: true
    type: string
  GH_TOKEN:
    required: true
    type: string
  OPENAI_API_KEY:
    required: true
    type: string
  ATTEMPTS:
    required: true
    type: string
  
runs:
  using: "composite"
  steps:
    - name: "Check attempts"
      shell: bash
      run:  |
        if [[ "${{ inputs.ATTEMPTS }}" -ge 3 ]]; then
          echo "YA NO QUEDAN INTENTOS DISPONIBLES..."
          exit 1
        fi

    - name: "Clone Gemini repository"
      shell: bash
      run: git clone https://${{ env.GH_TOKEN }}@github.com/Drastyn/create-image-gpt.git
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: "Install requirements"
      shell: bash
      run: pip install -r create-image-gpt/requirements.txt

    - name: "Get prompt"
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.input-artifact }}
        path: ${{ github.workspace }}/${{ inputs.input-artifact }}

    - name: "Image generation"
      shell: bash
      run: |
        prompt=$(cat ${{ github.workspace }}/${{ inputs.input-artifact }}/${{ inputs.prompt-file }})
        python3 create-image-gpt/main.py "$prompt"
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        IMAGE_NAME: ${{ inputs.image-name }}

    - name: "Upload image"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output-artifact }}
        path: ${{ github.workspace }}/${{ inputs.image-name }}.png
        retention-days: 1

    - name: "Update attempts"
      shell: bash
      run: python3 create-image-gpt/update_attempts.py
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        ATTEMPTS: ${{ inputs.ATTEMPTS }}
 
